### ISSUE TITLE
Problems when upgrading from sbt 0.13.x to 1.x ?

### ISSUE THREAD

**Issue by ranchoiver** [heroku/heroku-buildpack-scala#125]
I've bumped version of sbt and sbt-native-packager to latest available, and started getting these errors in every build:

```
       [info] Compiling 2 Scala sources to /tmp/scala_buildpack_build_dir/.sbt_home/plugins/target/scala-2.12/sbt-1.0/classes ...

       [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.3. Compiling...

       [info]   Compilation completed in 17.479s.

       [error] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin_sbt1.scala:4:8: HerokuBuildpackPlugin is already defined as object HerokuBuildpackPlugin

       [error] object HerokuBuildpackPlugin extends AutoPlugin {

       [error]        ^

       [error] one error found

       [error] (compile:compileIncremental) Compilation failed

       Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

 !     ERROR: Failed to run sbt!
```

I've tried to build with `heroku config:set SBT_CLEAN=true` , but it still fails.
What I'm doing wrong?

**Comment by jkutner** [comment]
This most likely means the buildpack is not recognizing your app as an sbt 1.0.0 app. It does this by [matching a regex for `sbt.version`](https://github.com/heroku/heroku-buildpack-scala/blob/3f6fb8ad47da5b0df2535de095c40f1492f5f66e/lib/common.sh#L6) in `project/build.properties` file. Can you show me the contents of your `project/build.properties` file?

**Comment by ranchoiver** [comment]
@jkutner 
`sbt.version = 1.0.2` (with spaces on both sides of equals sign)

build works with `sbt.version = 0.13.16`

**Comment by jkutner** [comment]
@ranchoiver can you try removing the spaces to see if that fixes it?

**Comment by jamesward** [comment]
Same error for me when upgrading.  My `project/build.properties` contains:
```
sbt.version=1.0.2
```

Same error with `heroku config:set SBT_CLEAN=true`

**Comment by jamesward** [comment]
Clearing the build cache did the trick: https://kb.heroku.com/how-do-i-clear-the-build-cache

**Comment by jamesward** [comment]
Note that this doesn't clear the build cache for Heroku CI so that still failed with the same error.
